name: hjnzb
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.1+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter
  # 存储
#  shared_preferences: 2.0.7
  get_storage: 2.0.3
  #Websoket
  web_socket_channel: ^2.2.0
  # 提示
  flutter_easyloading: 3.0.3
  # 下拉刷新
  pull_to_refresh: 2.0.0
  # 状态管理
  provider: 6.0.1
  get: 4.3.8
  # 图片缓存 不支持web
#  cached_network_image: 3.0.0
  extended_image: 4.1.0
  #网格布局 瀑布流
  flutter_staggered_grid_view: ^0.4.0

  # 图片选择
  image_picker: 0.8.2
  card_swiper: 1.0.4

  # 图片选择器 不支持web
#  wechat_assets_picker: 5.5.8
#  wechat_camera_picker: 2.2.0

  # 选择器
  flutter_pickers: 2.1.9
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  # 锁屏
  wakelock: 0.6.1+1
  # ping
#  dart_ping_ios: 1.0.0
  dart_ping_ios:
    path: plugins/dart_ping_ios
#  dart_ping: 6.1.1

  # 声网直播
  agora_rtc_engine: 5.1.0
#    git:
#      url: https://github.com/Tonigt/Agora-Flutter-SDK.git
  #  权限处理插件依赖项
  permission_handler: 6.0.0
#  # tencent im
#  tencent_im_sdk_plugin: 3.4.4
  # 验证码
  pin_code_fields: 7.3.0
  # 设备信息
  device_info_plus: 3.1.1
  # 视频播放器
  video_player: 2.2.7
  # 文本跑马灯
  marquee: 2.2.0
  # Banner
  flutter_swiper :  ^1.1.6
#  # gif 播放
#  gif_view: ^0.0.1
  # 软件包信息
#  package_info_plus: 1.3.0
  package_info_plus: 1.4.2
#  package_info_plus:
#    git:
#      url: https://github.com/Tonigt/plus_plugins.git
#      path: packages/package_info_plus/package_info_plus
#
#  package_info_plus_platform_interface:
#    git:
#      url: https://github.com/Tonigt/plus_plugins.git
#      path: packages/package_info_plus/package_info_plus_platform_interface

  # 应用
  url_launcher: 6.0.17
  install_plugin_v2: 1.0.0
#  open_file: 3.2.1
  # 环信im
  im_flutter_sdk: 3.9.0+1
#    git:
#      url: https://github.com/easemob/im_flutter_sdk.git
#      ref: flutter2_dev
  #  tencent_trtc_cloud:
#    git:
#      url: https://github.com/Tonigt/tencent_trtc_cloud.git
#      ref: txlite_smart


  httpplugin:
    path: plugins/http_manager
#    git: https://gitee.com/Tonight_embrace/http_manager.git

  firebase_messaging: 11.2.4
  flutter_local_notifications: 8.2.0
  firebase_auth: 3.3.9
  google_sign_in: 5.2.4
  google_sign_in_web: 0.10.0+5
#  flutter_login_facebook: 1.4.1
  #加密
  crypto: 3.0.1
  #uuid
  uuid: 3.0.5
  # ios  keyChain
#  flutter_keychain:
#    git:
#      url: https://github.com/Tonigt/flutter_keychain.git
  # 设备是否越狱
  flutter_jailbreak_detection: ^1.8.0
  # sim 卡信息
#  sim_info:
#    git:
#      url: https://github.com/Tonigt/flutter_sim_info.git

  # 本地ip
#  local_ip: 0.0.2
#  local_ip:
#    git:
#      url: https://github.com/Tonigt/flutter_localip_plugin.git

  # 唯一标识符
  unique_ids: ^3.0.0
  appscheme: 1.0.8

  # 保存文件到相册
  image_gallery_saver:
    path: plugins/image_gallery_saver

  # 二维码
  qr_flutter: 4.0.0

  # html 字符串显示
  flutter_html:
    path: plugins/flutter_html

#  webview_flutter:
#    git:
#      url: git://github.com/danqzt/webview_flutter-1.0.7.droid_fullscreen.git
#      ref: master

dev_dependencies:
  flutter_test:
    sdk: flutter

#dependency_overrides:
#  httpplugin:
#    path: ../../Tonight、相拥/http_manager
#  flutter_html:
#    path: ../../github_fork/flutter_html
#  wakelock: 0.6.1+1
#  flutter_keychain:
#    path: ../../github_fork/flutter_keychain
#  local_ip:
#    path: ../../github_fork/flutter_localip_plugin
#  sim_info:
#    path: ../../github_fork/flutter_sim_info
#  package_info_plus:
#    path: ../../github_fork/plus_plugins/packages/package_info_plus/package_info_plus
#  package_info_plus_platform_interface:
#    path: ../../github_fork/plus_plugins/packages/package_info_plus/package_info_plus_platform_interface

#  agora_rtc_engine:
#    path: ../../github_fork/Agora-Flutter-SDK
#  tencent_trtc_cloud:
#    path: ../../github_fork/tencent_trtc_cloud


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/grade/
    - assets/images/newsreader/
    - assets/video/

  fonts:
    - family: Number
      fonts:
        - asset: fonts/DIN-Medium.otf

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages


